	var quizArray = [{
		"id":"0",
		"question":"Qatar",
		"choice1":"Kampala",
		"choice2":"Doha",
		"choice3":"Dodoma",
		"correct":"Doha"
	},
	{
		"id":"1",
		"question":"Singapore",
		"choice1":"Phnom Penh",
		"choice2":"Singapore",
		"choice3":"Bangkok",
		"correct":"Singapore"
	},
	{
		"id":"2",
		"question":"Philippines",
		"choice1":"Cebu",
		"choice2":"Olongapo City",
		"choice3":"Manila",
		"correct":"Manila"
	},
	{
		"id":"3",
		"question":"Jordan",
		"choice1":"Astana",
		"choice2":"Amman",
		"choice3":"Bishkek",
		"correct":"Bishkek"
	},
	{
		"id":"4",
		"question":"Bahrain",
		"choice1":"Manama",
		"choice2":"Astana",
		"choice3":"Manila",
		"correct":"Manama"
	},
	{
		"id":"5",
		"question":"Panama",
		"choice1":"Panama City",
		"choice2":"Podgorica",
		"choice3":"Asuncion",
		"correct":"Panama City"
	},
	{
		"id":"6",
		"question":"South Africa",
		"choice1":"Bridgetown",
		"choice2":"Pretoria",
		"choice3":"Johannesburg",
		"correct":"Pretoria"
	},
	{
		"id":"7",
		"question":"Niger",
		"choice1":"Niamey",
		"choice2":"Abuja",
		"choice3":"Nairobi",
		"correct":"Niamey"
	},
	{
		"id":"8",
		"question":"Congo",
		"choice1":"Monrovia",
		"choice2":"Kinshasa",
		"choice3":"Brazzaville",
		"correct":"Brazzaville"
	},
	{
		"id":"9",
		"question":"Nigeria",
		"choice1":"Managua",
		"choice2":"Niamey",
		"choice3":"Abuja",
		"correct":"Abuja"
	},
	{
		"id":"10",
		"question":"Egypt",
		"choice1":"Rabat",
		"choice2":"Cairo",
		"choice3":"Luxor",
		"correct":"Cairo"
	},
	{
		"id":"11",
		"question":"Gabon",
		"choice1":"Accra",
		"choice2":"Banjul",
		"choice3":"Libreville",
		"correct":"Libreville"
	},
	{
		"id":"12",
		"question":"Guinea",
		"choice1":"Malabo",
		"choice2":"Conakry",
		"choice3":"Bissau",
		"correct":"Conakry"
	},
	{
		"id":"13",
		"question":"Angola",
		"choice1":"Lusaka",
		"choice2":"Lilongwe",
		"choice3":"Luanda",
		"correct":"Luanda"
	},
	{
		"id":"14",
		"question":"Morocco",
		"choice1":"Rabat",
		"choice2":"Marrakesh",
		"choice3":"Casablanca",
		"correct":"Rabat"
	},
	{
		"id":"15",
		"question":"Madagascar",
		"choice1":"Antananarivo",
		"choice2":"Madagascar",
		"choice3":"Montevideo",
		"correct":"Antananarivo"
	},
	{
		"id":"16",
		"question":"Uganda",
		"choice1":"Muscat",
		"choice2":"Abuja",
		"choice3":"Kampala",
		"correct":"Kampala"
	},
	{
		"id":"17",
		"question":"New Zealand",
		"choice1":"Canberra",
		"choice2":"Wellington",
		"choice3":"Melbourne",
		"correct":"Wellington"
	},
	{
		"id":"18",
		"question":"Australia",
		"choice1":"Canberra",
		"choice2":"Melbourne",
		"choice3":"Sydney",
		"correct":"Canberra"
	},
	{
		"id":"19",
		"question":"Japan",
		"choice1":"Tokyo",
		"choice2":"Ottawa",
		"choice3":"Kyoto",
		"correct":"Tokyo"
	},
	{
		"id":"20",
		"question":"Thailand",
		"choice1":"Taipei",
		"choice2":"Bangkok",
		"choice3":"Pyongyang",
		"correct":"Bangkok"
	},
	{
		"id":"21",
		"question":"Iraq",
		"choice1":"Baghdad",
		"choice2":"Tehran",
		"choice3":"Beirut",
		"correct":"Baghdad"
	},
	{
		"id":"22",
		"question":"Cambodia",
		"choice1":"Pyongyang",
		"choice2":"Bangkok",
		"choice3":"Phnom Penh",
		"correct":"Phnom Penh"
	},
	{
		"id":"23",
		"question":"Nepal",
		"choice1":"Kathmandu",
		"choice2":"Khartoum",
		"choice3":"Kuala Lumpur",
		"correct":"Kathmandu"
	},
	{
		"id":"24",
		"question":"Lebanon",
		"choice1":"Baghdad",
		"choice2":"Kabul",
		"choice3":"Beirut",
		"correct":"Beirut"
	},
	{
		"id":"25",
		"question":"Vietnam",
		"choice1":"Hanoi",
		"choice2":"Phnom Penh",
		"choice3":"Saulu",
		"correct":"Hanoi"
	},
	{
		"id":"26",
		"question":"United Arab Emirates",
		"choice1":"Addis Ababa",
		"choice2":"Ulan Bator",
		"choice3":"Abu Dhabi",
		"correct":"Abu Dhabi"
	},
	{
		"id":"27",
		"question":"Brunei",
		"choice1":"Brunei",
		"choice2":"Thimphu",
		"choice3":"Bandar Seri Begawan",
		"correct":"Bandar Seri Begawan"
	},
	{
		"id":"28",
		"question":"Portugal",
		"choice1":"Madrid",
		"choice2":"Lisbon",
		"choice3":"Barcelona",
		"correct":"Lisbon"
	},
	{
		"id":"29",
		"question":"Russia",
		"choice1":"Moscow",
		"choice2":"Saint-Petersbourg",
		"choice3":"Bucharest",
		"correct":"Moscow"
	},
	{
		"id":"30",
		"question":"Greece",
		"choice1":"Heraklion",
		"choice2":"Skopje",
		"choice3":"Athens",
		"correct":"Athens"
	},
	{
		"id":"31",
		"question":"England",
		"choice1":"Dublin",
		"choice2":"London",
		"choice3":"Belfast",
		"correct":"London"
	},
	{
		"id":"32",
		"question":"Netherlands",
		"choice1":"Cardiff",
		"choice2":"Amsterdam",
		"choice3":"Venice",
		"correct":"Amsterdam"
	},
	{
		"id":"33",
		"question":"Italy",
		"choice1":"Rome",
		"choice2":"Milan",
		"choice3":"Prague",
		"correct":"Rome"
	},
	{
		"id":"34",
		"question":"Ukraine",
		"choice1":"Belgrade",
		"choice2":"Prague",
		"choice3":"Kiev",
		"correct":"Kiev"
	},
	{
		"id":"35",
		"question":"Poland",
		"choice1":"Warsaw",
		"choice2":"Budapest",
		"choice3":"Montenegro",
		"correct":"Warsaw"
	},
	{
		"id":"36",
		"question":"France",
		"choice1":"Andorra",
		"choice2":"Paris",
		"choice3":"Monaco",
		"correct":"Paris"
	},
	{
		"id":"37",
		"question":"Canada",
		"choice1":"Toronto",
		"choice2":"Winnipeg",
		"choice3":"Ottawa",
		"correct":"Ottawa"
	},
	{
		"id":"38",
		"question":"Scotland",
		"choice1":"Dublin",
		"choice2":"Belfast",
		"choice3":"Edinburgh",
		"correct":"Edinburgh"
	},
	{
		"id":"39",
		"question":"Denmark",
		"choice1":"Copenhagen",
		"choice2":"Amsterdam",
		"choice3":"Dublin",
		"correct":"Copenhagen"
	},
	{
		"id":"40",
		"question":"Spain",
		"choice1":"Barcelona",
		"choice2":"Madrid",
		"choice3":"Lisbon",
		"correct":"Madrid"
	},
	{
		"id":"41",
		"question":"Germany",
		"choice1":"Berlin",
		"choice2":"Vienna",
		"choice3":"Geneva",
		"correct":"Berlin"
	},
	{
		"id":"42",
		"question":"Costa Rica",
		"choice1":"San Salvador",
		"choice2":"Havana",
		"choice3":"San Jose",
		"correct":"San Jose"
	},
	{
		"id":"43",
		"question":"Mexico",
		"choice1":"Mexico",
		"choice2":"Asuncion",
		"choice3":"Quito",
		"correct":"Mexico"
	},
	{
		"id":"44",
		"question":"Ecuador",
		"choice1":"Lima",
		"choice2":"Ecuador",
		"choice3":"Quito",
		"correct":"Quito"
	},
	{
		"id":"45",
		"question":"United States",
		"choice1":"New York",
		"choice2":"Kingston",
		"choice3":"Washington D.C.",
		"correct":"Washington D.C."
	},
	{
		"id":"46",
		"question":"Jamaica",
		"choice1":"Kingston",
		"choice2":"Pretoria",
		"choice3":"Port-au-Prince",
		"correct":"Kingston"
	},
	{
		"id":"47",
		"question":"Brazil",
		"choice1":"Buenos Aires",
		"choice2":"Brasilia",
		"choice3":"Havana",
		"correct":"Brasilia"
	},
	{
		"id":"48",
		"question":"Argentina",
		"choice1":"Havana",
		"choice2":"San Jose",
		"choice3":"Buenos Aires",
		"correct":"Buenos Aires"
	},
	{
		"id":"49",
		"question":"Haiti",
		"choice1":"Santo Domingo",
		"choice2":"Port Vila",
		"choice3":"Port-au-Prince",
		"correct":"Port-au-Prince"
	},
	{
		"id":"50",
		"question":"Peru",
		"choice1":"Isa",
		"choice2":"Dalawa",
		"choice3":"Lima",
		"correct":"Lima"
	},
	{
		"id":"51",
		"question":"Venezuela",
		"choice1":"Caracas",
		"choice2":"Montevideo",
		"choice3":"Port of Spain",
		"correct":"Caracas"
	},
	{
		"id":"52",
		"question":"Trinidad and Tobago",
		"choice1":"Port of Spain",
		"choice2":"Trinidad and Tobago",
		"choice3":"Port Vila",
		"correct":"Port of Spain"
	},
	{
		"id":"53",
		"question":"Bangladesh",
		"choice1":"Dhaka",
		"choice2":"Thimphu",
		"choice3":"Belmopan",
		"correct":"Dhaka"
	},
	{
		"id":"54",
		"question":"Wales",
		"choice1":"London",
		"choice2":"Cardiff",
		"choice3":"Amsterdam",
		"correct":"Cardiff"
	},
	{
		"id":"55",
		"question":"Botswana",
		"choice1":"Luanda",
		"choice2":"Algiers",
		"choice3":"Gaborone",
		"correct":"Gaborone"
	},
	{
		"id":"56",
		"question":"China",
		"choice1":"Beijing",
		"choice2":"Macau",
		"choice3":"Chinese",
		"correct":"Beijing"
	},
	{
		"id":"57",
		"question":"Armenia",
		"choice1":"Tirana",
		"choice2":"Tbilisi",
		"choice3":"Yerevan",
		"correct":"Yerevan"
	},
	{
		"id":"58",
		"question":"Oman",
		"choice1":"Managua",
		"choice2":"Abuja",
		"choice3":"Muscat",
		"correct":"Muscat"
	},
	{
		"id":"59",
		"question":"Israel",
		"choice1":"Amman",
		"choice2":"Jerusalem",
		"choice3":"Beirut",
		"correct":"Jerusalem"
	},
	{
		"id":"60",
		"question":"Sri Lanka",
		"choice1":"Colombo",
		"choice2":"Ljubljana",
		"choice3":"Sri Jayawardenapura Kotte",
		"correct":"Sri Jayawardenapura Kotte"
	},
	{
		"id":"61",
		"question":"Syria",
		"choice1":"Kinshasa",
		"choice2":"Bamako",
		"choice3":"Damascus",
		"correct":"Damascus"
	},
	{
		"id":"62",
		"question":"Belgium",
		"choice1":"Brussels",
		"choice2":"Gallia",
		"choice3":"Walloon",
		"correct":"Brussels"
	},
	{
		"id":"63",
		"question":"Cyprus",
		"choice1":"New Delhi",
		"choice2":"Nicosia",
		"choice3":"Erbil",
		"correct":"Nicosia"
	},
	{
		"id":"64",
		"question":"Uruguay",
		"choice1":"Montevideo",
		"choice2":"Monte-carlo",
		"choice3":"Antananarivo",
		"correct":"Montevideo"
	},
	{
		"id":"65",
		"question":"Bolivia",
		"choice1":"Zagreb",
		"choice2":"Sucre",
		"choice3":"San Jose",
		"correct":"Sucre"
	},
	{
		"id":"66",
		"question":"Saint Lucia",
		"choice1":"Cardiff",
		"choice2":"Port of Spain",
		"choice3":"Castries",
		"correct":"Castries"
	},
	{
		"id":"67",
		"question":"Estonia",
		"choice1":"Sofia",
		"choice2":"Gibraltar",
		"choice3":"Tallinn",
		"correct":"Tallinn"
	},
	{
		"id":"68",
		"question":"Norway",
		"choice1":"Podgorica",
		"choice2":"Vilnius",
		"choice3":"Oslo",
		"correct":"Oslo"
	},
	{
		"id":"69",
		"question":"Montenegro",
		"choice1":"Podgorica",
		"choice2":"Monaco",
		"choice3":"Riga",
		"correct":"Podgorica"
	},
	{
		"id":"70",
		"question":"Belarus",
		"choice1":"Minsk",
		"choice2":"Vienna",
		"choice3":"Brussels",
		"correct":"Minsk"
	},
	{
		"id":"71",
		"question":"Albania",
		"choice1":"Mariehamn",
		"choice2":"Tirana",
		"choice3":"Lek",
		"correct":"Tirana"
	},
	{
		"id":"72",
		"question":"Vatican City",
		"choice1":"Vatican City",
		"choice2":"Kiev",
		"choice3":"Bern",
		"correct":"Vatican City"
	},
	{
		"id":"73",
		"question":"Switzerland",
		"choice1":"Stockholm",
		"choice2":"Gallia",
		"choice3":"Bern",
		"correct":"Bern"
	},
	{
		"id":"74",
		"question":"Cuba",
		"choice1":"Belmopan",
		"choice2":"Belize",
		"choice3":"Havana",
		"correct":"Havana"
	},
	{
		"id":"75",
		"question":"Dominican Republic",
		"choice1":"Roseau",
		"choice2":"Santo Domingo",
		"choice3":"San Jose",
		"correct":"Santo Domingo"
	},
	{
		"id":"76",
		"question":"Greenland",
		"choice1":"Nuuk",
		"choice2":"Willemstad",
		"choice3":"Walloon",
		"correct":"Nuuk"
	},
	{
		"id":"77",
		"question":"Honduras",
		"choice1":"Plymouth",
		"choice2":"Tegucigalpa",
		"choice3":"Managua",
		"correct":"Tegucigalpa"
	},
	{
		"id":"78",
		"question":"Puerto Rico",
		"choice1":"San Juan",
		"choice2":"San Antonio",
		"choice3":"San Marcelino",
		"correct":"San Juan"
	},
	{
		"id":"79",
		"question":"Chile",
		"choice1":"Domingo",
		"choice2":"Georgetown",
		"choice3":"Santiago",
		"correct":"Santiago"
	},
	{
		"id":"80",
		"question":"United Kingdom",
		"choice1":"London",
		"choice2":"Vatican City",
		"choice3":"Belmopan",
		"correct":"London"
	},
	{
		"id":"81",
		"question":"Turkey",
		"choice1":"Ankara",
		"choice2":"Tashkent",
		"choice3":"Dushanbe",
		"correct":"Ankara"
	},
	{
		"id":"82",
		"question":"Yemen",
		"choice1":"Damascus",
		"choice2":"Sana'a",
		"choice3":"Ashgabat",
		"correct":"Sana'a"
	},
	{
		"id":"83",
		"question":"Taiwan",
		"choice1":"Taipei",
		"choice2":"Gaza",
		"choice3":"Islamabad",
		"correct":"Taipei"
	},
	{
		"id":"84",
		"question":"Pakistan",
		"choice1":"Islamabad",
		"choice2":"Muscat",
		"choice3":"Oman",
		"correct":"Islamabad"
	},
	{
		"id":"85",
		"question":"Saudi Arabia",
		"choice1":"Riyadh",
		"choice2":"Israel",
		"choice3":"Dubai",
		"correct":"Riyadh"
	},
	{
		"id":"86",
		"question":"Myanmar",
		"choice1":"Male",
		"choice2":"Kathmandu",
		"choice3":"Naypyidaw",
		"correct":"Naypyidaw"
	},
	{
		"id":"87",
		"question":"Maldives",
		"choice1":"Stepanakert",
		"choice2":"Vientiane",
		"choice3":"Male",
		"correct":"Male"
	},
	{
		"id":"88",
		"question":"Kuwait",
		"choice1":"Erbil",
		"choice2":"Ringgit",
		"choice3":"Kuwait City",
		"correct":"Kuwait City"
	},
	{
		"id":"89",
		"question":"Bhutan",
		"choice1":"Thimphu",
		"choice2":"Dhaka",
		"choice3":"Nicosia",
		"correct":"Thimphu"
	},
	{
		"id":"90",
		"question":"Afghanistan",
		"choice1":"Manama",
		"choice2":"Kabul",
		"choice3":"Yerevan",
		"correct":"Kabul"
	},
	{
		"id":"91",
		"question":"Zimbabwe",
		"choice1":"Kampala",
		"choice2":"Tunis",
		"choice3":"Harare",
		"correct":"Harare"
	},
	{
		"id":"92",
		"question":"Kenya",
		"choice1":"Nairobi",
		"choice2":"Gallia",
		"choice3":"Bissau",
		"correct":"Nairobi"
	},
	{
		"id":"93",
		"question":"Ghana",
		"choice1":"Banjul",
		"choice2":"Accra",
		"choice3":"Asmara",
		"correct":"Accra"
	},
	{
		"id":"94",
		"question":"Czech Republic",
		"choice1":"Helsinki",
		"choice2":"Tallinn",
		"choice3":"Prague",
		"correct":"Prague"
	},
	{
		"id":"95",
		"question":"Finland",
		"choice1":"Helsinki",
		"choice2":"Sarajevo",
		"choice3":"Danish",
		"correct":"Helsinki"
	},
	{
		"id":"96",
		"question":"Hungary",
		"choice1":"Douglas",
		"choice2":"Dublin",
		"choice3":"Budapest",
		"correct":"Budapest"
	},
	{
		"id":"97",
		"question":"Ireland",
		"choice1":"Dublin",
		"choice2":"Riga",
		"choice3":"Vaduz",
		"correct":"Dublin"
	},
	{
		"id":"98",
		"question":"San Marino",
		"choice1":"San Narciso",
		"choice2":"San Felife",
		"choice3":"San Marino",
		"correct":"San Marino"
	},
	{
		"id":"99",
		"question":"Serbia",
		"choice1":"Belgrade",
		"choice2":"Bratislava",
		"choice3":"Bucharest",
		"correct":"Belgrade"
	}];